### ISSUE TITLE
Line numbers without dots

### ISSUE THREAD

**Issue by ai** [hhsnopek/code-frame#10]
Right now you have a got after line number (`2.`):

```
  2. | function (foo) {
> 3. |         console.log(foo
     |                        ^
  4. |
```

But, `babel-code-frame`, doesn’t have it (just `2`):

```
  2 | function (foo) {
> 3 |         console.log(foo
    |                        ^
  4 |
```

@hhsnopek I want to use your awesome library in PostCSS, but I really need same output as in Babel (consistency UI is awesome)

**Comment by ai** [comment]
We could add option to not break compatibility

**Comment by hhsnopek** [comment]
Let's do it, wanna PR it in for credit?

## 

Henry Snopek

**Comment by ai** [comment]
Sure. What options name do you prefer? (my English is not best for API naming :D)

**Comment by hhsnopek** [comment]
🤔 actually I'm contemplating just removing it all together - thoughts?

## 

Henry Snopek

**Comment by ai** [comment]
awesome! :) I agree

**Comment by hhsnopek** [comment]
If you wanna submit a PR that'd be great - make sure to update the readme
examples and the tests 🙂

## 

Henry Snopek

**Comment by ai** [comment]
Hope I didn’t forget anything :) https://github.com/hhsnopek/code-frame/pull/11

**Comment by hhsnopek** [comment]
I'll take a look tonight when I'm at my computer, thanks!

## 

Henry Snopek

**Comment by ai** [comment]
Thanks for fast reply :)

**Comment by hhsnopek** [comment]
published @ai - thanks again for the PR!
