### ISSUE TITLE
Space before line number

### ISSUE THREAD

**Issue by ai** [hhsnopek/code-frame#14]
`code-frame` inserts space before line number: `" > 3"`, but `babel-code-frame` [doesn’t](https://github.com/babel/babel/blob/master/packages/babel-code-frame/src/index.js#L107).

I think we should take Babel’s style:
1. Consistency is always good.
2. Less symbols is better :D.

**Comment by hhsnopek** [comment]
The was a personal preference to add better pad the frames. I know that this is forcing users to have an additional char but adding this small "gutter" helps see the offending line. Though when I'm looking at a couple of local examples that have the stack trace with them, it doesn't line up with the stack trace. Wanna take the credit with a PR?

**Comment by ai** [comment]
Sure, I agree that this difference with Babel is not really mater. I am OK with this pad too :)
