### ISSUE TITLE
Differences from babel-code-frame?

### ISSUE THREAD

**Issue by hzoo** [hhsnopek/code-frame#9]
I see in the readme this is a smaller babel-code-frame, so was wondering what in particular made it slow/dependencies so we can improve it.

Would appreciate ideas/PRs if there's something that doesn't need to be there?

**Comment by hhsnopek** [comment]
Hey @hzoo - the reason I created this package was to create a minimal version of babel-code-frame that had little or no dependencies (... `left-pad`). I also wanted to remove the weight of color support which isn't necessary for terminal use and these extra dependencies: `jsTokens, esutils`

**Comment by hzoo** [comment]
Ah ok makes sense. I guess we'd want color support still.

`js-tokens` isn't much: https://unpkg.com/js-tokens@2.0.0 and we are only using esutils for es6 keywords which can be inlined.

**Comment by hhsnopek** [comment]
😄 did anything in here throw some flags? - it's pretty small hah

**Comment by hzoo** [comment]
No I just happened to see this looking at `babel-` packages on npm 👍. Wondered how we could make it more consumable for others
